"""Shared NDI SDK bindings used by both input and output modules."""

from .lib import (
    NDI_BANDWIDTH_HIGHEST,
    NDI_BANDWIDTH_LOWEST,
    NDI_COLOR_FORMAT_BGRX_BGRA,
    NDI_COLOR_FORMAT_RGBX_RGBA,
    NDI_COLOR_FORMAT_UYVY_BGRA,
    NDI_COLOR_FORMAT_UYVY_RGBA,
    NDI_FOURCC_BGRA,
    NDI_FOURCC_BGRX,
    NDI_FOURCC_RGBA,
    NDI_FOURCC_RGBX,
    NDI_FOURCC_UYVY,
    NDI_FRAME_TYPE_AUDIO,
    NDI_FRAME_TYPE_METADATA,
    NDI_FRAME_TYPE_VIDEO,
    NDIlib_audio_frame_v2_t,
    NDIlib_find_create_t,
    NDIlib_metadata_frame_t,
    NDIlib_recv_create_v3_t,
    NDIlib_send_create_t,
    NDIlib_source_t,
    NDIlib_video_frame_v2_t,
    is_available,
    load_library,
    setup_recv_functions,
    setup_send_functions,
)

__all__ = [
    "NDIlib_audio_frame_v2_t",
    "NDIlib_find_create_t",
    "NDIlib_metadata_frame_t",
    "NDIlib_recv_create_v3_t",
    "NDIlib_send_create_t",
    "NDIlib_source_t",
    "NDIlib_video_frame_v2_t",
    "NDI_BANDWIDTH_HIGHEST",
    "NDI_BANDWIDTH_LOWEST",
    "NDI_COLOR_FORMAT_BGRX_BGRA",
    "NDI_COLOR_FORMAT_RGBX_RGBA",
    "NDI_COLOR_FORMAT_UYVY_BGRA",
    "NDI_COLOR_FORMAT_UYVY_RGBA",
    "NDI_FOURCC_BGRA",
    "NDI_FOURCC_BGRX",
    "NDI_FOURCC_RGBA",
    "NDI_FOURCC_RGBX",
    "NDI_FOURCC_UYVY",
    "NDI_FRAME_TYPE_AUDIO",
    "NDI_FRAME_TYPE_METADATA",
    "NDI_FRAME_TYPE_VIDEO",
    "is_available",
    "load_library",
    "setup_recv_functions",
    "setup_send_functions",
]
